# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.oauth2_oauth2_write import Oauth2Oauth2Write

class TestOauth2Oauth2Write(unittest.TestCase):
    """Oauth2Oauth2Write unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2Oauth2Write:
        """Test Oauth2Oauth2Write
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2Oauth2Write`
        """
        model = Oauth2Oauth2Write()
        if include_optional:
            return Oauth2Oauth2Write(
                grant_type = 'client_credentials',
                client_id = '',
                client_secret = ''
            )
        else:
            return Oauth2Oauth2Write(
        )
        """

    def testOauth2Oauth2Write(self):
        """Test Oauth2Oauth2Write"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
