# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.definition_jsonld_definition_read_context import DefinitionJsonldDefinitionReadContext

class TestDefinitionJsonldDefinitionReadContext(unittest.TestCase):
    """DefinitionJsonldDefinitionReadContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionJsonldDefinitionReadContext:
        """Test DefinitionJsonldDefinitionReadContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionJsonldDefinitionReadContext`
        """
        model = DefinitionJsonldDefinitionReadContext()
        if include_optional:
            return DefinitionJsonldDefinitionReadContext(
                vocab = '',
                hydra = 'http://www.w3.org/ns/hydra/core#'
            )
        else:
            return DefinitionJsonldDefinitionReadContext(
                vocab = '',
                hydra = 'http://www.w3.org/ns/hydra/core#',
        )
        """

    def testDefinitionJsonldDefinitionReadContext(self):
        """Test DefinitionJsonldDefinitionReadContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
