# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.entity_jsonld_entity_read_entity_read_parent import EntityJsonldEntityReadEntityReadParent

class TestEntityJsonldEntityReadEntityReadParent(unittest.TestCase):
    """EntityJsonldEntityReadEntityReadParent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityJsonldEntityReadEntityReadParent:
        """Test EntityJsonldEntityReadEntityReadParent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityJsonldEntityReadEntityReadParent`
        """
        model = EntityJsonldEntityReadEntityReadParent()
        if include_optional:
            return EntityJsonldEntityReadEntityReadParent(
                context = None,
                id = '',
                type = '',
                id = '',
                slug = '',
                data = jsonhub_sdk.models.data.data(),
                definition = jsonhub_sdk.models.definition/jsonld_entity/read_entity/read/parent.definition.jsonld-entity.read_entity.read.parent(
                    @context = null, 
                    @id = '', 
                    @type = '', 
                    id = '', 
                    slug = '', ),
                parent = jsonhub_sdk.models.entity/jsonld_entity/read_entity/read/parent.entity.jsonld-entity.read_entity.read.parent(
                    @context = null, 
                    @id = '', 
                    @type = '', 
                    id = '', 
                    slug = '', 
                    data = jsonhub_sdk.models.data.data(), 
                    definition = jsonhub_sdk.models.definition/jsonld_entity/read_entity/read/parent.definition.jsonld-entity.read_entity.read.parent(
                        @id = '', 
                        @type = '', 
                        id = '', 
                        slug = '', ), 
                    parent = jsonhub_sdk.models.entity/jsonld_entity/read_entity/read/parent.entity.jsonld-entity.read_entity.read.parent(
                        @id = '', 
                        @type = '', 
                        id = '', 
                        slug = '', 
                        data = jsonhub_sdk.models.data.data(), 
                        private = True, 
                        is_owned_by_current_user = True, ), 
                    private = True, 
                    is_owned_by_current_user = True, ),
                private = True,
                is_owned_by_current_user = True
            )
        else:
            return EntityJsonldEntityReadEntityReadParent(
        )
        """

    def testEntityJsonldEntityReadEntityReadParent(self):
        """Test EntityJsonldEntityReadEntityReadParent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
