# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.definition_jsonld_definition_write import DefinitionJsonldDefinitionWrite

class TestDefinitionJsonldDefinitionWrite(unittest.TestCase):
    """DefinitionJsonldDefinitionWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionJsonldDefinitionWrite:
        """Test DefinitionJsonldDefinitionWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionJsonldDefinitionWrite`
        """
        model = DefinitionJsonldDefinitionWrite()
        if include_optional:
            return DefinitionJsonldDefinitionWrite(
                slug = '',
                json_schema = None,
                parent_entity = 'https://example.com/'
            )
        else:
            return DefinitionJsonldDefinitionWrite(
                json_schema = None,
        )
        """

    def testDefinitionJsonldDefinitionWrite(self):
        """Test DefinitionJsonldDefinitionWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
