# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.entity_entity_read_entity_read_parent import EntityEntityReadEntityReadParent

class TestEntityEntityReadEntityReadParent(unittest.TestCase):
    """EntityEntityReadEntityReadParent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityEntityReadEntityReadParent:
        """Test EntityEntityReadEntityReadParent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityEntityReadEntityReadParent`
        """
        model = EntityEntityReadEntityReadParent()
        if include_optional:
            return EntityEntityReadEntityReadParent(
                id = '',
                slug = '',
                data = jsonhub_sdk.models.data.data(),
                definition = jsonhub_sdk.models.entity_definition/read.entity-definition.read(
                    id = '', 
                    slug = '', ),
                parent = jsonhub_sdk.models.entity_entity/read_entity/read/parent.entity-entity.read_entity.read.parent(
                    id = '', 
                    slug = '', 
                    data = jsonhub_sdk.models.data.data(), 
                    definition = jsonhub_sdk.models.entity_definition/read.entity-definition.read(
                        id = '', 
                        slug = '', ), 
                    parent = jsonhub_sdk.models.entity_entity/read_entity/read/parent.entity-entity.read_entity.read.parent(
                        id = '', 
                        slug = '', 
                        data = jsonhub_sdk.models.data.data(), 
                        private = True, 
                        is_owned_by_current_user = True, ), 
                    private = True, 
                    is_owned_by_current_user = True, ),
                private = True,
                is_owned_by_current_user = True
            )
        else:
            return EntityEntityReadEntityReadParent(
        )
        """

    def testEntityEntityReadEntityReadParent(self):
        """Test EntityEntityReadEntityReadParent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
