# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.api_definitions_get_collection200_response_embedded_any_of import ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf

class TestApiDefinitionsGetCollection200ResponseEmbeddedAnyOf(unittest.TestCase):
    """ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf:
        """Test ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf`
        """
        model = ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf()
        if include_optional:
            return ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf(
                item = [
                    jsonhub-sdk.models.definition/jsonhal_definition/read.definition.jsonhal-definition.read(
                        _links = jsonhub-sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                            self = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                                href = '', ), ), 
                        id = '', 
                        slug = '', 
                        json_schema = jsonhub-sdk.models.json_schema.jsonSchema(), 
                        parent_entity = jsonhub-sdk.models.entity/jsonhal_definition/read.entity.jsonhal-definition.read(
                            id = '', 
                            slug = '', ), 
                        is_owned_by_current_user = True, )
                    ]
            )
        else:
            return ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf(
        )
        """

    def testApiDefinitionsGetCollection200ResponseEmbeddedAnyOf(self):
        """Test ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
