# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.api_entities_get_collection200_response_embedded import ApiEntitiesGetCollection200ResponseEmbedded

class TestApiEntitiesGetCollection200ResponseEmbedded(unittest.TestCase):
    """ApiEntitiesGetCollection200ResponseEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiEntitiesGetCollection200ResponseEmbedded:
        """Test ApiEntitiesGetCollection200ResponseEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiEntitiesGetCollection200ResponseEmbedded`
        """
        model = ApiEntitiesGetCollection200ResponseEmbedded()
        if include_optional:
            return ApiEntitiesGetCollection200ResponseEmbedded(
                item = [
                    jsonhub_sdk.models.entity/jsonhal_entity/read_entity/read/parent.entity.jsonhal-entity.read_entity.read.parent(
                        _links = jsonhub_sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                            self = jsonhub_sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                                href = '', ), ), 
                        id = '', 
                        slug = '', 
                        data = jsonhub_sdk.models.data.data(), 
                        definition = jsonhub_sdk.models.entity/jsonhal_definition/read.entity.jsonhal-definition.read(
                            id = '', 
                            slug = '', ), 
                        parent = jsonhub_sdk.models.entity/jsonhal_entity/read_entity/read/parent.entity.jsonhal-entity.read_entity.read.parent(
                            id = '', 
                            slug = '', 
                            data = jsonhub_sdk.models.data.data(), 
                            private = True, 
                            is_owned_by_current_user = True, ), 
                        private = True, 
                        is_owned_by_current_user = True, )
                    ]
            )
        else:
            return ApiEntitiesGetCollection200ResponseEmbedded(
        )
        """

    def testApiEntitiesGetCollection200ResponseEmbedded(self):
        """Test ApiEntitiesGetCollection200ResponseEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
