# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.api.entity_api import EntityApi


class TestEntityApi(unittest.TestCase):
    """EntityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EntityApi()

    def tearDown(self) -> None:
        pass

    def test_api_entities_get_collection(self) -> None:
        """Test case for api_entities_get_collection

        Retrieves the collection of entity resources.
        """
        pass

    def test_api_entities_id_delete(self) -> None:
        """Test case for api_entities_id_delete

        Removes the entity resource.
        """
        pass

    def test_api_entities_id_get(self) -> None:
        """Test case for api_entities_id_get

        Retrieves a entity resource.
        """
        pass

    def test_api_entities_id_patch(self) -> None:
        """Test case for api_entities_id_patch

        Updates the entity resource.
        """
        pass

    def test_api_entities_post(self) -> None:
        """Test case for api_entities_post

        Creates a entity resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
