# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.api_definitions_get_collection200_response_links import ApiDefinitionsGetCollection200ResponseLinks

class TestApiDefinitionsGetCollection200ResponseLinks(unittest.TestCase):
    """ApiDefinitionsGetCollection200ResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDefinitionsGetCollection200ResponseLinks:
        """Test ApiDefinitionsGetCollection200ResponseLinks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDefinitionsGetCollection200ResponseLinks`
        """
        model = ApiDefinitionsGetCollection200ResponseLinks()
        if include_optional:
            return ApiDefinitionsGetCollection200ResponseLinks(
                var_self = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                    href = '', ),
                first = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                    href = '', ),
                last = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                    href = '', ),
                next = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                    href = '', ),
                previous = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                    href = '', )
            )
        else:
            return ApiDefinitionsGetCollection200ResponseLinks(
        )
        """

    def testApiDefinitionsGetCollection200ResponseLinks(self):
        """Test ApiDefinitionsGetCollection200ResponseLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
