# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.definition_definition_read import DefinitionDefinitionRead

class TestDefinitionDefinitionRead(unittest.TestCase):
    """DefinitionDefinitionRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionDefinitionRead:
        """Test DefinitionDefinitionRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionDefinitionRead`
        """
        model = DefinitionDefinitionRead()
        if include_optional:
            return DefinitionDefinitionRead(
                id = '',
                slug = '',
                json_schema = None,
                parent_entity = jsonhub-sdk.models.entity_definition/read.entity-definition.read(
                    id = '', 
                    slug = '', ),
                is_owned_by_current_user = True
            )
        else:
            return DefinitionDefinitionRead(
                json_schema = None,
        )
        """

    def testDefinitionDefinitionRead(self):
        """Test DefinitionDefinitionRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
