# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.api.oauth2_api import Oauth2Api


class TestOauth2Api(unittest.TestCase):
    """Oauth2Api unit test stubs"""

    def setUp(self) -> None:
        self.api = Oauth2Api()

    def tearDown(self) -> None:
        pass

    def test_api_oauth2token_post(self) -> None:
        """Test case for api_oauth2token_post

        Retrieve an OAuth2 Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
