# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.user_jsonapi_data import UserJsonapiData

class TestUserJsonapiData(unittest.TestCase):
    """UserJsonapiData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserJsonapiData:
        """Test UserJsonapiData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserJsonapiData`
        """
        model = UserJsonapiData()
        if include_optional:
            return UserJsonapiData(
                id = '',
                type = '',
                attributes = jsonhub-sdk.models.user_jsonapi_data_attributes.user_jsonapi_data_attributes(
                    _id = '', 
                    email = '', 
                    password = '', 
                    old_password = '', 
                    token = '', 
                    reset_password_link = '', 
                    activation_url = '', )
            )
        else:
            return UserJsonapiData(
                id = '',
                type = '',
        )
        """

    def testUserJsonapiData(self):
        """Test UserJsonapiData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
