# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.definition_entity_read_entity_read_parent import DefinitionEntityReadEntityReadParent

class TestDefinitionEntityReadEntityReadParent(unittest.TestCase):
    """DefinitionEntityReadEntityReadParent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionEntityReadEntityReadParent:
        """Test DefinitionEntityReadEntityReadParent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionEntityReadEntityReadParent`
        """
        model = DefinitionEntityReadEntityReadParent()
        if include_optional:
            return DefinitionEntityReadEntityReadParent(
                id = '',
                slug = ''
            )
        else:
            return DefinitionEntityReadEntityReadParent(
        )
        """

    def testDefinitionEntityReadEntityReadParent(self):
        """Test DefinitionEntityReadEntityReadParent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
