# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.api_definitions_get_collection200_response_links_self import ApiDefinitionsGetCollection200ResponseLinksSelf

class TestApiDefinitionsGetCollection200ResponseLinksSelf(unittest.TestCase):
    """ApiDefinitionsGetCollection200ResponseLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDefinitionsGetCollection200ResponseLinksSelf:
        """Test ApiDefinitionsGetCollection200ResponseLinksSelf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDefinitionsGetCollection200ResponseLinksSelf`
        """
        model = ApiDefinitionsGetCollection200ResponseLinksSelf()
        if include_optional:
            return ApiDefinitionsGetCollection200ResponseLinksSelf(
                href = ''
            )
        else:
            return ApiDefinitionsGetCollection200ResponseLinksSelf(
        )
        """

    def testApiDefinitionsGetCollection200ResponseLinksSelf(self):
        """Test ApiDefinitionsGetCollection200ResponseLinksSelf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
