# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.user_user_create import UserUserCreate

class TestUserUserCreate(unittest.TestCase):
    """UserUserCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUserCreate:
        """Test UserUserCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUserCreate`
        """
        model = UserUserCreate()
        if include_optional:
            return UserUserCreate(
                email = '',
                password = '',
                activation_url = ''
            )
        else:
            return UserUserCreate(
                email = '',
                password = '',
        )
        """

    def testUserUserCreate(self):
        """Test UserUserCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
