# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.user_user_resend_activation import UserUserResendActivation

class TestUserUserResendActivation(unittest.TestCase):
    """UserUserResendActivation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUserResendActivation:
        """Test UserUserResendActivation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUserResendActivation`
        """
        model = UserUserResendActivation()
        if include_optional:
            return UserUserResendActivation(
                email = '',
                activation_url = ''
            )
        else:
            return UserUserResendActivation(
                email = '',
        )
        """

    def testUserUserResendActivation(self):
        """Test UserUserResendActivation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
