# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.user_jsonhal_user_resend_activation import UserJsonhalUserResendActivation

class TestUserJsonhalUserResendActivation(unittest.TestCase):
    """UserJsonhalUserResendActivation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserJsonhalUserResendActivation:
        """Test UserJsonhalUserResendActivation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserJsonhalUserResendActivation`
        """
        model = UserJsonhalUserResendActivation()
        if include_optional:
            return UserJsonhalUserResendActivation(
                links = jsonhub-sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                    self = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), ),
                email = '',
                activation_url = ''
            )
        else:
            return UserJsonhalUserResendActivation(
                email = '',
        )
        """

    def testUserJsonhalUserResendActivation(self):
        """Test UserJsonhalUserResendActivation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
