# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.definition_jsonhal_definition_read import DefinitionJsonhalDefinitionRead

class TestDefinitionJsonhalDefinitionRead(unittest.TestCase):
    """DefinitionJsonhalDefinitionRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionJsonhalDefinitionRead:
        """Test DefinitionJsonhalDefinitionRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionJsonhalDefinitionRead`
        """
        model = DefinitionJsonhalDefinitionRead()
        if include_optional:
            return DefinitionJsonhalDefinitionRead(
                links = jsonhub_sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                    self = jsonhub_sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), ),
                id = '',
                slug = '',
                json_schema = None,
                parent_entity = jsonhub_sdk.models.entity/jsonhal_definition/read.entity.jsonhal-definition.read(
                    _links = jsonhub_sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                        self = jsonhub_sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                            href = '', ), ), 
                    id = '', 
                    slug = '', ),
                is_owned_by_current_user = True
            )
        else:
            return DefinitionJsonhalDefinitionRead(
                json_schema = None,
        )
        """

    def testDefinitionJsonhalDefinitionRead(self):
        """Test DefinitionJsonhalDefinitionRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
