# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.user_jsonapi import UserJsonapi

class TestUserJsonapi(unittest.TestCase):
    """UserJsonapi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserJsonapi:
        """Test UserJsonapi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserJsonapi`
        """
        model = UserJsonapi()
        if include_optional:
            return UserJsonapi(
                data = jsonhub_sdk.models.user_jsonapi_data.user_jsonapi_data(
                    id = '', 
                    type = '', 
                    attributes = jsonhub_sdk.models.user_jsonapi_data_attributes.user_jsonapi_data_attributes(
                        _id = '', 
                        email = '', 
                        password = '', 
                        old_password = '', 
                        token = '', 
                        reset_password_link = '', 
                        activation_url = '', ), )
            )
        else:
            return UserJsonapi(
        )
        """

    def testUserJsonapi(self):
        """Test UserJsonapi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
