# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.entity_jsonhal_entity_create import EntityJsonhalEntityCreate

class TestEntityJsonhalEntityCreate(unittest.TestCase):
    """EntityJsonhalEntityCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityJsonhalEntityCreate:
        """Test EntityJsonhalEntityCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityJsonhalEntityCreate`
        """
        model = EntityJsonhalEntityCreate()
        if include_optional:
            return EntityJsonhalEntityCreate(
                links = jsonhub-sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                    self = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), ),
                slug = '',
                data = None,
                definition = 'https://example.com/',
                parent = jsonhub-sdk.models.entity/jsonhal_entity/create.entity.jsonhal-entity.create(
                    _links = jsonhub-sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                        self = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                            href = '', ), ), 
                    slug = '', 
                    data = jsonhub-sdk.models.data.data(), 
                    definition = 'https://example.com/', 
                    parent = jsonhub-sdk.models.entity/jsonhal_entity/create.entity.jsonhal-entity.create(
                        slug = '', 
                        data = jsonhub-sdk.models.data.data(), 
                        definition = 'https://example.com/', 
                        private = True, ), 
                    private = True, ),
                private = True
            )
        else:
            return EntityJsonhalEntityCreate(
        )
        """

    def testEntityJsonhalEntityCreate(self):
        """Test EntityJsonhalEntityCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
