# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.oauth2_oauth2_read import Oauth2Oauth2Read

class TestOauth2Oauth2Read(unittest.TestCase):
    """Oauth2Oauth2Read unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2Oauth2Read:
        """Test Oauth2Oauth2Read
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2Oauth2Read`
        """
        model = Oauth2Oauth2Read()
        if include_optional:
            return Oauth2Oauth2Read(
                access_token = ''
            )
        else:
            return Oauth2Oauth2Read(
        )
        """

    def testOauth2Oauth2Read(self):
        """Test Oauth2Oauth2Read"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
