# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.api_definitions_get_collection200_response import ApiDefinitionsGetCollection200Response

class TestApiDefinitionsGetCollection200Response(unittest.TestCase):
    """ApiDefinitionsGetCollection200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDefinitionsGetCollection200Response:
        """Test ApiDefinitionsGetCollection200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDefinitionsGetCollection200Response`
        """
        model = ApiDefinitionsGetCollection200Response()
        if include_optional:
            return ApiDefinitionsGetCollection200Response(
                embedded = None,
                total_items = 0,
                items_per_page = 0,
                links = jsonhub-sdk.models.api_definitions_get_collection_200_response__links.api_definitions_get_collection_200_response__links(
                    self = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), 
                    first = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), 
                    last = , 
                    next = , 
                    previous = , )
            )
        else:
            return ApiDefinitionsGetCollection200Response(
                embedded = None,
                links = jsonhub-sdk.models.api_definitions_get_collection_200_response__links.api_definitions_get_collection_200_response__links(
                    self = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), 
                    first = jsonhub-sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), 
                    last = , 
                    next = , 
                    previous = , ),
        )
        """

    def testApiDefinitionsGetCollection200Response(self):
        """Test ApiDefinitionsGetCollection200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
