# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.definition_definition_write import DefinitionDefinitionWrite

class TestDefinitionDefinitionWrite(unittest.TestCase):
    """DefinitionDefinitionWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionDefinitionWrite:
        """Test DefinitionDefinitionWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionDefinitionWrite`
        """
        model = DefinitionDefinitionWrite()
        if include_optional:
            return DefinitionDefinitionWrite(
                slug = '',
                json_schema = None,
                parent_entity = 'https://example.com/'
            )
        else:
            return DefinitionDefinitionWrite(
                json_schema = None,
        )
        """

    def testDefinitionDefinitionWrite(self):
        """Test DefinitionDefinitionWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
