# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.api.definition_api import DefinitionApi


class TestDefinitionApi(unittest.TestCase):
    """DefinitionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefinitionApi()

    def tearDown(self) -> None:
        pass

    def test_api_definitions_get_collection(self) -> None:
        """Test case for api_definitions_get_collection

        Retrieves the collection of definition resources.
        """
        pass

    def test_api_definitions_id_delete(self) -> None:
        """Test case for api_definitions_id_delete

        Removes the definition resource.
        """
        pass

    def test_api_definitions_id_get(self) -> None:
        """Test case for api_definitions_id_get

        Retrieves a definition resource.
        """
        pass

    def test_api_definitions_id_patch(self) -> None:
        """Test case for api_definitions_id_patch

        Updates the definition resource.
        """
        pass

    def test_api_definitions_post(self) -> None:
        """Test case for api_definitions_post

        Creates a definition resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
