# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_api_users_id_delete(self) -> None:
        """Test case for api_users_id_delete

        Removes the user resource.
        """
        pass

    def test_api_users_id_patch(self) -> None:
        """Test case for api_users_id_patch

        Updates the user resource.
        """
        pass

    def test_api_users_post(self) -> None:
        """Test case for api_users_post

        Creates a user resource.
        """
        pass

    def test_api_usersresend_activation_post(self) -> None:
        """Test case for api_usersresend_activation_post

        Resend activation email
        """
        pass

    def test_api_usersreset_password_post(self) -> None:
        """Test case for api_usersreset_password_post

        Reset password (with token)
        """
        pass

    def test_api_userssend_reset_password_post(self) -> None:
        """Test case for api_userssend_reset_password_post

        Send reset password email
        """
        pass


if __name__ == '__main__':
    unittest.main()
