# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.user_jsonhal import UserJsonhal

class TestUserJsonhal(unittest.TestCase):
    """UserJsonhal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserJsonhal:
        """Test UserJsonhal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserJsonhal`
        """
        model = UserJsonhal()
        if include_optional:
            return UserJsonhal(
                links = jsonhub_sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                    self = jsonhub_sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), ),
                id = '',
                email = '',
                password = '',
                old_password = '',
                token = '',
                reset_password_link = '',
                activation_url = ''
            )
        else:
            return UserJsonhal(
                email = '',
        )
        """

    def testUserJsonhal(self):
        """Test UserJsonhal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
