# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.oauth2_jsonapi_data import Oauth2JsonapiData

class TestOauth2JsonapiData(unittest.TestCase):
    """Oauth2JsonapiData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2JsonapiData:
        """Test Oauth2JsonapiData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2JsonapiData`
        """
        model = Oauth2JsonapiData()
        if include_optional:
            return Oauth2JsonapiData(
                id = '',
                type = '',
                attributes = jsonhub-sdk.models.oauth2_jsonapi_data_attributes.oauth2_jsonapi_data_attributes(
                    grant_type = 'client_credentials', 
                    client_id = '', 
                    client_secret = '', 
                    access_token = '', )
            )
        else:
            return Oauth2JsonapiData(
                id = '',
                type = '',
        )
        """

    def testOauth2JsonapiData(self):
        """Test Oauth2JsonapiData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
