# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.definition_jsonld_definition_read import DefinitionJsonldDefinitionRead

class TestDefinitionJsonldDefinitionRead(unittest.TestCase):
    """DefinitionJsonldDefinitionRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionJsonldDefinitionRead:
        """Test DefinitionJsonldDefinitionRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionJsonldDefinitionRead`
        """
        model = DefinitionJsonldDefinitionRead()
        if include_optional:
            return DefinitionJsonldDefinitionRead(
                context = None,
                id = '',
                type = '',
                id = '',
                slug = '',
                json_schema = None,
                parent_entity = jsonhub-sdk.models.entity/jsonld_definition/read.entity.jsonld-definition.read(
                    @context = null, 
                    @id = '', 
                    @type = '', 
                    id = '', 
                    slug = '', ),
                is_owned_by_current_user = True
            )
        else:
            return DefinitionJsonldDefinitionRead(
                json_schema = None,
        )
        """

    def testDefinitionJsonldDefinitionRead(self):
        """Test DefinitionJsonldDefinitionRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
