# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.oauth2_jsonhal_oauth2_write import Oauth2JsonhalOauth2Write

class TestOauth2JsonhalOauth2Write(unittest.TestCase):
    """Oauth2JsonhalOauth2Write unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2JsonhalOauth2Write:
        """Test Oauth2JsonhalOauth2Write
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2JsonhalOauth2Write`
        """
        model = Oauth2JsonhalOauth2Write()
        if include_optional:
            return Oauth2JsonhalOauth2Write(
                links = jsonhub_sdk.models.definition_jsonhal_definition_read__links.definition_jsonhal_definition_read__links(
                    self = jsonhub_sdk.models.api_definitions_get_collection_200_response__links_self.api_definitions_get_collection_200_response__links_self(
                        href = '', ), ),
                grant_type = 'client_credentials',
                client_id = '',
                client_secret = ''
            )
        else:
            return Oauth2JsonhalOauth2Write(
        )
        """

    def testOauth2JsonhalOauth2Write(self):
        """Test Oauth2JsonhalOauth2Write"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
