# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.oauth2_jsonapi import Oauth2Jsonapi

class TestOauth2Jsonapi(unittest.TestCase):
    """Oauth2Jsonapi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2Jsonapi:
        """Test Oauth2Jsonapi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2Jsonapi`
        """
        model = Oauth2Jsonapi()
        if include_optional:
            return Oauth2Jsonapi(
                data = jsonhub_sdk.models.oauth2_jsonapi_data.oauth2_jsonapi_data(
                    id = '', 
                    type = '', 
                    attributes = jsonhub_sdk.models.oauth2_jsonapi_data_attributes.oauth2_jsonapi_data_attributes(
                        grant_type = 'client_credentials', 
                        client_id = '', 
                        client_secret = '', 
                        access_token = '', ), )
            )
        else:
            return Oauth2Jsonapi(
        )
        """

    def testOauth2Jsonapi(self):
        """Test Oauth2Jsonapi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
