# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.entity_entity_update import EntityEntityUpdate

class TestEntityEntityUpdate(unittest.TestCase):
    """EntityEntityUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityEntityUpdate:
        """Test EntityEntityUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityEntityUpdate`
        """
        model = EntityEntityUpdate()
        if include_optional:
            return EntityEntityUpdate(
                slug = '',
                data = None,
                parent = jsonhub-sdk.models.entity_entity/update.entity-entity.update(
                    slug = '', 
                    data = jsonhub-sdk.models.data.data(), 
                    parent = jsonhub-sdk.models.entity_entity/update.entity-entity.update(
                        slug = '', 
                        data = jsonhub-sdk.models.data.data(), 
                        private = True, ), 
                    private = True, ),
                private = True
            )
        else:
            return EntityEntityUpdate(
        )
        """

    def testEntityEntityUpdate(self):
        """Test EntityEntityUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
