# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub-sdk.models.definition_jsonapi import DefinitionJsonapi

class TestDefinitionJsonapi(unittest.TestCase):
    """DefinitionJsonapi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionJsonapi:
        """Test DefinitionJsonapi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionJsonapi`
        """
        model = DefinitionJsonapi()
        if include_optional:
            return DefinitionJsonapi(
                data = jsonhub-sdk.models.definition_jsonapi_data.definition_jsonapi_data(
                    id = '', 
                    type = '', 
                    attributes = jsonhub-sdk.models.definition_jsonapi_data_attributes.definition_jsonapi_data_attributes(
                        _id = '', 
                        slug = '', 
                        json_schema = jsonhub-sdk.models.json_schema.jsonSchema(), ), ),
                parent_entity = jsonhub-sdk.models.entity/jsonapi.entity.jsonapi(
                    id = '', 
                    slug = '', 
                    data = jsonhub-sdk.models.data.data(), 
                    definition = jsonhub-sdk.models.definition/jsonapi.definition.jsonapi(
                        data = jsonhub-sdk.models.definition_jsonapi_data.definition_jsonapi_data(
                            id = '', 
                            type = '', 
                            attributes = jsonhub-sdk.models.definition_jsonapi_data_attributes.definition_jsonapi_data_attributes(
                                _id = '', 
                                slug = '', 
                                json_schema = jsonhub-sdk.models.json_schema.jsonSchema(), ), ), 
                        parent_entity = jsonhub-sdk.models.entity/jsonapi.entity.jsonapi(
                            id = '', 
                            slug = '', 
                            parent = , 
                            private = True, 
                            is_owned_by_current_user = True, ), 
                        is_owned_by_current_user = True, ), 
                    parent = , 
                    private = True, 
                    is_owned_by_current_user = True, ),
                is_owned_by_current_user = True
            )
        else:
            return DefinitionJsonapi(
        )
        """

    def testDefinitionJsonapi(self):
        """Test DefinitionJsonapi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
