# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.definition_jsonapi_data import DefinitionJsonapiData

class TestDefinitionJsonapiData(unittest.TestCase):
    """DefinitionJsonapiData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionJsonapiData:
        """Test DefinitionJsonapiData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionJsonapiData`
        """
        model = DefinitionJsonapiData()
        if include_optional:
            return DefinitionJsonapiData(
                id = '',
                type = '',
                attributes = jsonhub_sdk.models.definition_jsonapi_data_attributes.definition_jsonapi_data_attributes(
                    _id = '', 
                    slug = '', 
                    json_schema = jsonhub_sdk.models.json_schema.jsonSchema(), )
            )
        else:
            return DefinitionJsonapiData(
                id = '',
                type = '',
        )
        """

    def testDefinitionJsonapiData(self):
        """Test DefinitionJsonapiData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
