# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jsonhub_sdk.models.user_user_update import UserUserUpdate

class TestUserUserUpdate(unittest.TestCase):
    """UserUserUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUserUpdate:
        """Test UserUserUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUserUpdate`
        """
        model = UserUserUpdate()
        if include_optional:
            return UserUserUpdate(
                password = '',
                old_password = ''
            )
        else:
            return UserUserUpdate(
                password = '',
        )
        """

    def testUserUserUpdate(self):
        """Test UserUserUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
