# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jsonhub_sdk.models.definition_jsonhal_definition_read_links import DefinitionJsonhalDefinitionReadLinks
from jsonhub_sdk.models.entity_jsonhal_definition_read import EntityJsonhalDefinitionRead
from typing import Optional, Set
from typing_extensions import Self

class DefinitionJsonhalDefinitionRead(BaseModel):
    """
    
    """ # noqa: E501
    links: Optional[DefinitionJsonhalDefinitionReadLinks] = Field(default=None, alias="_links")
    id: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    json_schema: Dict[str, Any] = Field(alias="jsonSchema")
    parent_entity: Optional[EntityJsonhalDefinitionRead] = Field(default=None, alias="parentEntity")
    is_owned_by_current_user: Optional[StrictBool] = Field(default=None, alias="isOwnedByCurrentUser")
    __properties: ClassVar[List[str]] = ["_links", "id", "slug", "jsonSchema", "parentEntity", "isOwnedByCurrentUser"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefinitionJsonhalDefinitionRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parent_entity
        if self.parent_entity:
            _dict['parentEntity'] = self.parent_entity.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        # set to None if parent_entity (nullable) is None
        # and model_fields_set contains the field
        if self.parent_entity is None and "parent_entity" in self.model_fields_set:
            _dict['parentEntity'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefinitionJsonhalDefinitionRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_links": DefinitionJsonhalDefinitionReadLinks.from_dict(obj["_links"]) if obj.get("_links") is not None else None,
            "id": obj.get("id"),
            "slug": obj.get("slug"),
            "jsonSchema": obj.get("jsonSchema"),
            "parentEntity": EntityJsonhalDefinitionRead.from_dict(obj["parentEntity"]) if obj.get("parentEntity") is not None else None,
            "isOwnedByCurrentUser": obj.get("isOwnedByCurrentUser")
        })
        return _obj


