# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, Optional
from jsonhub-sdk.models.api_entities_get_collection200_response_embedded_any_of import ApiEntitiesGetCollection200ResponseEmbeddedAnyOf
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

APIENTITIESGETCOLLECTION200RESPONSEEMBEDDED_ANY_OF_SCHEMAS = ["ApiEntitiesGetCollection200ResponseEmbeddedAnyOf", "object"]

class ApiEntitiesGetCollection200ResponseEmbedded(BaseModel):
    """
    ApiEntitiesGetCollection200ResponseEmbedded
    """

    # data type: ApiEntitiesGetCollection200ResponseEmbeddedAnyOf
    anyof_schema_1_validator: Optional[ApiEntitiesGetCollection200ResponseEmbeddedAnyOf] = None
    # data type: object
    anyof_schema_2_validator: Optional[Dict[str, Any]] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ApiEntitiesGetCollection200ResponseEmbeddedAnyOf, object]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "ApiEntitiesGetCollection200ResponseEmbeddedAnyOf", "object" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ApiEntitiesGetCollection200ResponseEmbedded.model_construct()
        error_messages = []
        # validate data type: ApiEntitiesGetCollection200ResponseEmbeddedAnyOf
        if not isinstance(v, ApiEntitiesGetCollection200ResponseEmbeddedAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ApiEntitiesGetCollection200ResponseEmbeddedAnyOf`")
        else:
            return v

        # validate data type: object
        try:
            instance.anyof_schema_2_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ApiEntitiesGetCollection200ResponseEmbedded with anyOf schemas: ApiEntitiesGetCollection200ResponseEmbeddedAnyOf, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ApiEntitiesGetCollection200ResponseEmbeddedAnyOf] = None
        try:
            instance.actual_instance = ApiEntitiesGetCollection200ResponseEmbeddedAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.anyof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_2_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ApiEntitiesGetCollection200ResponseEmbedded with anyOf schemas: ApiEntitiesGetCollection200ResponseEmbeddedAnyOf, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ApiEntitiesGetCollection200ResponseEmbeddedAnyOf, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


