# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jsonhub-sdk.models.definition_jsonld_entity_read_entity_read_parent import DefinitionJsonldEntityReadEntityReadParent
from jsonhub-sdk.models.definition_jsonld_entity_read_entity_read_parent_context import DefinitionJsonldEntityReadEntityReadParentContext
from typing import Optional, Set
from typing_extensions import Self

class EntityJsonldEntityReadEntityReadParent(BaseModel):
    """
    
    """ # noqa: E501
    context: Optional[DefinitionJsonldEntityReadEntityReadParentContext] = Field(default=None, alias="@context")
    id: Optional[StrictStr] = Field(default=None, alias="@id")
    type: Optional[StrictStr] = Field(default=None, alias="@type")
    id: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    data: Optional[Dict[str, Any]] = None
    definition: Optional[DefinitionJsonldEntityReadEntityReadParent] = None
    parent: Optional[EntityJsonldEntityReadEntityReadParent] = None
    private: Optional[StrictBool] = None
    is_owned_by_current_user: Optional[StrictBool] = Field(default=None, alias="isOwnedByCurrentUser")
    __properties: ClassVar[List[str]] = ["@context", "@id", "@type", "id", "slug", "data", "definition", "parent", "private", "isOwnedByCurrentUser"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityJsonldEntityReadEntityReadParent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "type",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['@context'] = self.context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of definition
        if self.definition:
            _dict['definition'] = self.definition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parent
        if self.parent:
            _dict['parent'] = self.parent.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        # set to None if definition (nullable) is None
        # and model_fields_set contains the field
        if self.definition is None and "definition" in self.model_fields_set:
            _dict['definition'] = None

        # set to None if parent (nullable) is None
        # and model_fields_set contains the field
        if self.parent is None and "parent" in self.model_fields_set:
            _dict['parent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityJsonldEntityReadEntityReadParent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@context": DefinitionJsonldEntityReadEntityReadParentContext.from_dict(obj["@context"]) if obj.get("@context") is not None else None,
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "id": obj.get("id"),
            "slug": obj.get("slug"),
            "data": obj.get("data"),
            "definition": DefinitionJsonldEntityReadEntityReadParent.from_dict(obj["definition"]) if obj.get("definition") is not None else None,
            "parent": EntityJsonldEntityReadEntityReadParent.from_dict(obj["parent"]) if obj.get("parent") is not None else None,
            "private": obj.get("private"),
            "isOwnedByCurrentUser": obj.get("isOwnedByCurrentUser")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
EntityJsonldEntityReadEntityReadParent.model_rebuild(raise_errors=False)

