# coding: utf-8

"""
    JsonHub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jsonhub-sdk.models.definition_jsonld_entity_read_entity_read_parent_context import DefinitionJsonldEntityReadEntityReadParentContext
from typing import Optional, Set
from typing_extensions import Self

class UserJsonld(BaseModel):
    """
    
    """ # noqa: E501
    context: Optional[DefinitionJsonldEntityReadEntityReadParentContext] = Field(default=None, alias="@context")
    id: Optional[StrictStr] = Field(default=None, alias="@id")
    type: Optional[StrictStr] = Field(default=None, alias="@type")
    id: Optional[StrictStr] = None
    email: Optional[StrictStr]
    password: Optional[StrictStr] = None
    old_password: Optional[StrictStr] = Field(default=None, alias="oldPassword")
    token: Optional[StrictStr] = None
    reset_password_link: Optional[StrictStr] = Field(default=None, alias="resetPasswordLink")
    activation_url: Optional[StrictStr] = Field(default=None, alias="activationUrl")
    __properties: ClassVar[List[str]] = ["@context", "@id", "@type", "id", "email", "password", "oldPassword", "token", "resetPasswordLink", "activationUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserJsonld from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "type",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['@context'] = self.context.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if old_password (nullable) is None
        # and model_fields_set contains the field
        if self.old_password is None and "old_password" in self.model_fields_set:
            _dict['oldPassword'] = None

        # set to None if token (nullable) is None
        # and model_fields_set contains the field
        if self.token is None and "token" in self.model_fields_set:
            _dict['token'] = None

        # set to None if reset_password_link (nullable) is None
        # and model_fields_set contains the field
        if self.reset_password_link is None and "reset_password_link" in self.model_fields_set:
            _dict['resetPasswordLink'] = None

        # set to None if activation_url (nullable) is None
        # and model_fields_set contains the field
        if self.activation_url is None and "activation_url" in self.model_fields_set:
            _dict['activationUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserJsonld from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@context": DefinitionJsonldEntityReadEntityReadParentContext.from_dict(obj["@context"]) if obj.get("@context") is not None else None,
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "id": obj.get("id"),
            "email": obj.get("email"),
            "password": obj.get("password"),
            "oldPassword": obj.get("oldPassword"),
            "token": obj.get("token"),
            "resetPasswordLink": obj.get("resetPasswordLink"),
            "activationUrl": obj.get("activationUrl")
        })
        return _obj


